theme: jekyll-theme-hacker
title: "Killerbyte Workshop"
description: "A small indie dev from Queensland, Australia."
lsi: false
safe: true
source: /
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge